### ISSUE TITLE
Achievements in live still not triggered

### ISSUE THREAD

**Issue by Faithy123** [Ayowel/renpy-epicgames-eos#5]
Hey. Thanks a lot for the extension, but after I did everything according to the given instructions - https://github.com/Ayowel/renpy-epicgames-eos/blob/master/README.adoc, I got this error on startup my game:

While running game code:
  File "game/epic.rpy", line 22, in script
    init -1499 python:
  File "game/epic.rpy", line 22, in script
    init -1499 python:
  File "game/epic.rpy", line 23, in <module>
    achievement.backends.insert(0, epicapi.EpicBackend())
NameError: name 'epicapi' is not defined

What could be the problem?

**Comment by Faithy123** [comment]
Ok, I managed to get the game to launch and the Epic Games overlay opens. But when I load the game distributions into live, the achievements are still not triggered. I guess it could be about config.epic_sandbox and config.epic_deployment, I need to take those values from the Live component, right? Not from Dev or Stage...

**Comment by Faithy123** [comment]
Problem solved, thanks a lot for your help!

**Comment by Ayowel** [comment]
There were two issues:
* There is a typo in the release of `v0.2.1` which is fixed by 356e596 .
* Epic Games does not systematically provide the Deployment ID to the game, so the definition of `config.epic_deployment` should be moved from `game/01epic_dev.rpy` to `game/epic.rpy`

To be fixed in `v0.2.2`
